### ISSUE TITLE
Add "main.h" file not found to FAQ

### ISSUE THREAD

**Issue by seendsouza** [purduesigbots/pros-docs#128] opened 2019-05-21 17:55 UTC
As @theol0403 mentioned on Discord, this issue seems to pop up a lot nowadays, so I'll add it to a FAQ if wanted. I'm not exactly sure where to put it though. The General Use FAQ is a bit general, the Coding FAQ that consists of run-time and compile-time issues don't categorize this issue (linter and compile_commands.json), and there's also the PROS FAQ.

**Comment by theol0403** [comment] 2019-05-21 18:03
The error of "main.h" not found is caused by invalid linter cache, and that is the first problem it encounters (as `main.h` is usually at the top of the file).
I wrote an [explanation](https://www.vexforum.com/t/main-h-not-found-linter/61970/3?u=theol0403) on VexForum, but it will have to be reworded for the docs.
We need to figure where to put it, and to what depth to explain.

**Comment by HotelCalifornia** [comment] 2019-05-21 21:10
As far as where to put it, I think it could go on the coding FAQ page either in a new section or just above the other two sections

**Comment by nathan-moore** [comment] 2020-01-05 16:03
This was fixed by #129

**Closed by nathan-moore** 2020-01-05 16:03 UTC
