### ISSUE TITLE
Okapi Motion Profiling Memory Permission Error

### ISSUE THREAD

**Issue by erikorlowski** [purduesigbots/pros-docs#104] opened 2019-02-10 22:17 UTC
When I run motion profiling and disable autonomous while a path is executing, a memory permission error is thrown.

[pros.zip](https://github.com/purduesigbots/pros-docs/files/2849464/pros.zip)

**Comment by baylessj** [comment] 2019-02-10 22:39
This is a duplicate of Okapilib/Okapilib#321, for which a fix is being worked on currently. In the meantime, I would recommend allocating your motion profile controller on the heap, this should prevent the error you are experiencing.

**Closed by baylessj** 2019-02-10 22:39 UTC
